
# POST http://localhost:8086/editora/cadastrar
# Content-Type: application/json

# {
#   "nome_editora": "AmandaEdits"
# }

# ### LISTAR
# GET http://localhost:8086/editora/listar

### DELETAR
# DELETE http://localhost:8086/editora/deletar
# Content-Type: application/json

# {
#   "nome_editora": "AlephEdits"
# }

# ### ATUALIZAR
# PUT http://localhost:8086/editora/2
# Content-Type: application/json

# {
#   "nome_editora": "NovaEditoraAtualizada"
# }



# POST http://localhost:8086/categoria/cadastrar
# Content-Type: application/json

# {
#   "nome_categoria": "fantasia"
# }

### LISTAR
# GET http://localhost:8086/categoria/listar

## DELETAR
# DELETE http://localhost:8086/categoria/deletar
# Content-Type: application/json

# {
#   "nome_categoria": "terror"
# }

# ### ATUALIZAR
# PUT http://localhost:8086/categoria/2
# Content-Type: application/json

# {
#   "nome_categoria": "NovacategoriaAtualizada"
# }

# GET http://localhost:8086/categoria/listar

PUT http://localhost:8086/categoria/2
Content-Type: application/json

{
  "nome_categoria": "NovaCategoriaAtualizada"
}
