# Cadastrar
POST http://localhost:8086/curso/cadastrar
Content-Type: application/json

{
  "nome_curso":"engenharia da pesca"
}

###

# Listar
GET http://localhost:8086/curso/listar

###

# Atualizar
PUT http://localhost:8086/curso/1
Content-Type: application/json

{
  "nome_curso": "Engenharia das top"
}

###

# Deletar
DELETE http://localhost:8086/curso/deletar
Content-Type: application/json

{
  "nome_curso": "Engenharia das top"
}

# # Cadastrar
# POST http://localhost:8086/categoria/cadastrar
# Content-Type: application/json

# {
#   "nome_categoria": "comedia"
# }

###

# Listar
GET http://localhost:8086/categoria/listar

###